import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<div className='hero min-h-screen bg-base-200'>
					<div className='hero-content text-center'>
						<div className='max-w-md'>
							<h1 className='font-bold text-5xl'>Assessment Link</h1>
							<p className='py-6'>
								Aplikasi yang berisi informasi mengenai instrumen tes
								berdasarkan taksonomi bloom revisi dan cara penyusunannya
							</p>
							<Link href='/login'>
								<button className='btn btn-primary mx-3 px-5'>Masuk</button>
							</Link>
							<Link href='/register'>
								<button className='btn btn-ghost mx-3 px-5'>Daftar</button>
							</Link>
						</div>
					</div>
				</div>
				<div className=''></div>
			</main>
		</>
	);
}
